### PR TITLE
Add emacs lsp-jq

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
@nverno ok to add? some additional instructions needed etc?

**Comment by nverno** [comment]
Hi, I was waiting on https://github.com/emacs-lsp/lsp-mode/pull/4140, which would make [nverno/lsp-jq](https://github.com/nverno/lsp-jq) unnecessary.  I'll keep you posted, thankyou!

**Comment by wader** [comment]
I see, great! thanks

**Comment by wader** [comment]
and let me know if there is something to do to make jq-lsp more emacs LSP friendly

**Comment by wader** [comment]
Oh noticed it fail on windows CI :( that has not been tested at all yet.  #5

**Comment by wader** [comment]
Hey, i noticed some activity on this. Let me know if this can be merge and/or if you want some changes... you can also do your own PR that replaces this one if you like.

**Comment by nverno** [comment]
Hey, it looks good! Just change the link from [lsp-jq](https://github.com/nverno/lsp-jq) to [lsp-mode](https://github.com/emacs-lsp/lsp-mode) now its merged. Thankyou!

**Comment by wader** [comment]
Nice, thanks!

**Pull request merged**
